[project]
name = "BookMaker25-04"
version = "25.04.0"
description = "A Book Authoring Application in Python"
authors = [
    {name = "Chris Brown", email = "chris@marcrisoft.co.uk"},
]
dependencies = [
    "mistune == 2.0.5",
    "pygments == 2.9.0"
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}
distribution = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pyrefly]
search_path = [
    "/home/chris/PycharmProjects/BookMaker25-04/src/bookmaker/..."
]
project_includes = ["**/*"]
project_excludes = [
    "**/.[!/.]*",
    "**/*venv/**/*",
]
